### PR TITLE
Remove unnecessary bower dependency to angular-ui-bootstrap-bower

### PR DESCRIPTION
**Pull request by gastonelhordoy**

### CODE REVIEW

**Comment by gastonelhordoy** [comment]
Hey, didn't notice tests were using that dependency, re-added it as a dev-dependency for node, since it's only needed for building.

**Comment by maxfierke** [comment]
Nice catch! Merging...

**Comment by gastonelhordoy** [comment]
Glad to help, thanks for sharing. BTW, are you planning to release this?

**Comment by maxfierke** [comment]
It should be up on bower already, I think?

**Comment by gastonelhordoy** [comment]
Not sure... Package version has not been increased for what I see

**Comment by maxfierke** [comment]
Oh, I didn't realize you meant the pull request. Since the change was to the `bower.json`, I'll just retag the release.

**Pull request merged**
